### ISSUE TITLE
Inconsistance in the ontology

### ISSUE THREAD

**Issue by klefevre** [snipsco/queries-ontology#2]
We found that there are some inconsistencies in the JSON:
- The domain and intent's type field has an `@` e.g. `"@type": "intent"`,  whereas the slot type field has an `@` in the value e.g. `"type": "@slot"`.
- The `question_for_tagging` field is in the snake case whereas the rest is in camel case.
- The `question_for_tagging` type is sometime a `String` and sometime an object.

**Comment by JDureau** [comment]
I fixed the 2 first points, thanks for pointing them out.
Regarding the third one, it's intended. We're using both options in the AMT tagging dashboard, depending on the cases. Is that a problem?

**Comment by fredszaq** [comment]
Not a real problem i'd say, as we don't use the field in the génération

Le 9 nov. 2016 4:20 PM, "Joseph Dureau" <notifications@github.com> a écrit :

I fixed the 2 first points, thanks for pointing them out.
Regarding the third one, it's intended. We're using both options in the AMT
tagging dashboard, depending on the cases. Is that a problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/snipsco/queries-ontology/issues/2#issuecomment-259439540>,
or mute the thread

**Comment by JDureau** [comment]
Cool, we can close this issue, then?

**Comment by klefevre** [comment]
Yes
